project:
  type: book

book:
  title: "Using snakemake to create robust and reproducible bioinformatic pipelines"
  author: "Dan MacLean"
  date: "10/25/2022"
  chapters:
    - index.qmd
    - intro.qmd
    - features.qmd
    - cluster.qmd
    - summary.qmd
    - checkout.qmd


format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



